default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: collections-apis_development

test:
  <<: *default
  database: collections-apis_test

production:
  <<: *default
  database: collections-apis_production
  username: collections-apis
  password: <%= ENV['COLLECTIONS-APIS_DATABASE_PASSWORD'] %>
